sudo: false

language: c

addons:
  apt:
    packages:
    - libgmp-dev

matrix:
  include:
  - env: ARGS="--resolver lts-6"
  - env: ARGS="--resolver lts-9"
  - env: ARGS="--resolver lts-10"
  - env: ARGS="--resolver nightly"
  allow_failures:
  - env: ARGS="--resolver nightly"

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script: stack $ARGS --no-terminal --install-ghc test --haddock

cache:
  directories:
  - $HOME/.stack
